# Generated by Django 2.2.2 on 2019-10-30 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Condiments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Condiments',
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('photo', models.FileField(upload_to='documents/dishes')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Category')),
            ],
            options={
                'verbose_name_plural': 'Dishes',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('pin', models.FloatField(max_length=4)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='documents/employees')),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Foodcombos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mix_ratio', models.FloatField()),
                ('unit_ratio', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Food Combos',
            },
        ),
        migrations.CreateModel(
            name='Imprest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'Imprest',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='documents/receipts/Invoice')),
            ],
            options={
                'verbose_name_plural': 'Invoice',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.FileField(upload_to='documents/suppliers')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('res', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Title',
            },
        ),
        migrations.CreateModel(
            name='System_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='documents/logo')),
                ('location', models.CharField(max_length=200)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'System Information',
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.FloatField()),
                ('quantity', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('receipt', models.FileField(upload_to='documents/receipts/supplies')),
                ('delivery_note', models.FileField(upload_to='documents/receipts/delivery_notes')),
                ('sup_date', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Supplier')),
            ],
            options={
                'verbose_name_plural': 'Supplies',
            },
        ),
        migrations.CreateModel(
            name='Stockflags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(max_length=100)),
                ('units', models.FloatField()),
                ('pub_date', models.DateTimeField()),
                ('photo', models.FileField(upload_to='documents/stockflags')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Dishes')),
            ],
            options={
                'verbose_name_plural': 'Stock Flags',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.FloatField()),
                ('pub_date', models.DateTimeField()),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Dishes')),
            ],
            options={
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('cost', models.FloatField()),
                ('conds', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Condiments')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Dishes')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='Pettycash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('pub_date', models.DateTimeField()),
                ('receipt', models.FileField(upload_to='documents/receipts/supplies')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'Petty Cash',
            },
        ),
        migrations.CreateModel(
            name='Petty_Cash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('units', models.FloatField()),
                ('quantity', models.CharField(max_length=20)),
                ('cost', models.FloatField()),
                ('receipt', models.FileField(upload_to='documents/receipts/petty')),
                ('pub_date', models.DateTimeField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'Petty Cash',
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('price', models.FloatField()),
                ('pub_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Customers')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Dishes')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Employees')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Lpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('photo', models.FileField(upload_to='documents/receipts/LPO')),
                ('location', models.CharField(max_length=200)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'Local Purchase Order',
            },
        ),
        migrations.CreateModel(
            name='Floor_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=100)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status')),
            ],
            options={
                'verbose_name_plural': 'Floor Plan',
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Title'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='food_combo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Foodcombos'),
        ),
        migrations.AddField(
            model_name='dishes',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status'),
        ),
        migrations.AddField(
            model_name='customers',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status'),
        ),
        migrations.AddField(
            model_name='condiments',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oposapp.Status'),
        ),
    ]
