# Generated by Django 2.2.2 on 2019-11-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oposapp', '0002_auto_20191031_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='pin',
            field=models.IntegerField(),
        ),
    ]
