from django.contrib import admin
from . import models

admin.site.register(models.Category)
admin.site.register(models.Orders)
admin.site.register(models.Stock)
admin.site.register(models.Supplier)
admin.site.register(models.Dishes)
admin.site.register(models.Supplies)
admin.site.register(models.Employees)
admin.site.register(models.Customers)
admin.site.register(models.Status)
admin.site.register(models.Title)
admin.site.register(models.Pettycash)
admin.site.register(models.System_info)
admin.site.register(models.Foodcombos)
admin.site.register(models.Invoice)
admin.site.register(models.Lpo)
admin.site.register(models.Imprest)
admin.site.register(models.Recipes)
admin.site.register(models.Stockflags)
admin.site.register(models.Floor_plan)